[package]
name = "hanoidb"
version = "0.1.0"
edition = "2021"

[dependencies]
crc32fast = "1.4.2"
derive_more = { version = "1.0.0", features = ["is_variant"] }
fastbloom = "0.7.1"
thiserror = "1.0.63"

[dev-dependencies]
tempfile = "3.13.0"
